[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/"
    weight = 1

[[main]]
    identifier = "newsletter"
    name = "Newsletter"
    url = "https://wiliamvj.substack.com/"
    weight = 2

# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/wiliamvj/"
    weight = 1

[[social]]
    identifier = "x"
    name = "x"
    url = "https://twitter.com/wiliamjoaquim"
    weight = 2

[[social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/wiliamvj"
    weight = 3

[[social]]
    identifier = "devto"
    name = "dev.to"
    url = "https://dev.to/wiliamvj"
    weight = 4