# Homepage Config
isSinglePage = true

# Meta Config
description = "Wiliam V. Joaquim - Software Developer"

# Header Configuration
avatar = "img/profile-picture.jpg"

#favicon
favicon = "icons/favicon.ico"
favicon16x16 = "icons/favicon-16x16.png"
favicon32x32 = "icons/favicon-32x32.png"
appleTouchIcon = "icons/apple-touch.png"
android192x192 = "icons/android-chrome-192x192.png"
android512x512 = "icons/android-chrome-512x512.png"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = true
    repo = "wiliamvj/wiliamvj.com"
    repoId = "R_kgDOKqMPTA"
    category = "General"
    categoryId = "DIC_kwDOKqMPTM4CbzWf"
    mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    theme = "dark"
    # lang = "zh-CN"
    lazyLoading = true